### ISSUE TITLE
`readline-complete` fails during Emacs 24.4 initialization

### ISSUE THREAD

**Issue by dholm** [monsanto/readline-complete.el#12]
This is triggered by the autoload for `(eval-after-load 'auto-complete [..]`.

    Debugger entered--Lisp error: (void-variable shell)
      #[nil "\301^H\302\"\207" [shell ac-define-source ((candidates . rlc-candidates) (prefix . ac-rlc-prefix-shell-dispatcher) (requires . 0))] 3]()
      eval-after-load-helper("/home/dholm/.emacs.d/el-get/auto-complete/auto-complete.elc")
      run-hook-with-args(eval-after-load-helper "/home/dholm/.emacs.d/el-get/auto-complete/auto-complete.elc")
      do-after-load-evaluation("/home/dholm/.emacs.d/el-get/auto-complete/auto-complete.elc")

**Comment by monsanto** [comment]
Should be fixed by #18
